from __future__ import annotations

import os
import re
from collections.abc import Mapping
from pathlib import Path


QUALITY_OPTIONS: dict[str, dict[str, str]] = {
    "low": {
        "graphicsMode": "fast",
        "renderDistance": "2",
        "simulationDistance": "5",
        "entityDistanceScaling": "0.5",
        "ao": "false",
        "biomeBlendRadius": "0",
        "renderClouds": '"false"',
        "particles": "0",
        "maxFps": "120",
        "enableVsync": "false",
        "bobView": "false",
        "fov": "0.0",
    },
    "medium": {
        "graphicsMode": "fancy",
        "renderDistance": "8",
        "simulationDistance": "5",
        "entityDistanceScaling": "1.0",
        "ao": "true",
        "biomeBlendRadius": "1",
        "renderClouds": '"false"',
        "particles": "1",
        "maxFps": "120",
        "enableVsync": "false",
    },
    "high": {
        "graphicsMode": "fabulous",
        "renderDistance": "12",
        "simulationDistance": "6",
        "entityDistanceScaling": "1.0",
        "ao": "true",
        "biomeBlendRadius": "2",
        "renderClouds": '"true"',
        "particles": "2",
        "maxFps": "120",
        "enableVsync": "false",
    },
}


QUIET_CAPTURE_OPTIONS: dict[str, str] = {
    "advancedItemTooltips": "false",
    "chatVisibility": "2",
    "inGameNotification": "false",
    "joinedFirstServer": "true",
    "mouseSensitivity": "0.5",
    "musicToast": '"never"',
    "notificationDisplayTime": "0.5",
    "pauseOnLostFocus": "false",
    "rawMouseInput": "true",
    "realmsNotifications": "false",
    "showAutosaveIndicator": "false",
    "showSubtitles": "false",
    "skipMultiplayerWarning": "true",
    "tutorialStep": "none",
}

_SHADER_OPTION_KEY_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
_SHADER_OPTION_VALUE_RE = re.compile(r"[A-Za-z0-9_.+\-]+\Z")
_SHADER_OPTIONS_COMMENT = "Generated by mcdata."


def write_options(
    work_dir: Path,
    *,
    quality: str,
    resourcepacks: list[str],
    overrides: dict[str, str] | None = None,
    quiet_capture: bool = True,
) -> None:
    options = dict(QUALITY_OPTIONS.get(quality, QUALITY_OPTIONS["low"]))
    if quiet_capture:
        options.update(QUIET_CAPTURE_OPTIONS)
    if overrides:
        options.update({str(key): str(value) for key, value in overrides.items()})
    if resourcepacks:
        options["resourcePacks"] = "[" + ",".join(f'"file/{name}"' for name in resourcepacks) + "]"
        options["incompatibleResourcePacks"] = "[]"

    lines = [f"{key}:{value}" for key, value in sorted(options.items())]
    (work_dir / "options.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


def validate_shader_options(options: Mapping[str, str] | None) -> dict[str, str]:
    if options is None:
        return {}
    if not isinstance(options, Mapping):
        raise ValueError("Iris shader_options must be a mapping of string keys to string values")

    normalized: dict[str, str] = {}
    for key, value in options.items():
        if not isinstance(key, str) or not _SHADER_OPTION_KEY_RE.fullmatch(key):
            raise ValueError(
                "Iris shader option keys must be GLSL-style identifiers "
                f"(invalid key: {key!r})"
            )
        if not isinstance(value, str) or not _SHADER_OPTION_VALUE_RE.fullmatch(value):
            raise ValueError(
                "Iris shader option values must be non-empty, single-token strings "
                f"(invalid value for {key!r}: {value!r})"
            )
        normalized[key] = value
    return dict(sorted(normalized.items()))


def write_iris_config(
    work_dir: Path,
    *,
    shaderpack: str | None,
    enabled: bool,
    shader_options: Mapping[str, str] | None = None,
) -> None:
    options = validate_shader_options(shader_options)
    shaderpack = _validate_shaderpack_filename(shaderpack)
    if options and shaderpack is None:
        raise ValueError("Iris shader_options require exactly one selected shader ZIP")

    config_dir = work_dir / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "iris.properties").write_text(
        "\n".join(
            [
                "# Generated by mcdata.",
                f"enableShaders={'true' if enabled and shaderpack else 'false'}",
                f"shaderPack={shaderpack or ''}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    if shaderpack is None:
        return
    sidecar = work_dir / "shaderpacks" / f"{shaderpack}.txt"
    sidecar.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write_bytes(
        sidecar,
        serialize_java_properties(options, comment=_SHADER_OPTIONS_COMMENT),
    )


def canonicalize_iris_shader_options_sidecar(
    work_dir: Path,
    *,
    shaderpack: str,
) -> Path:
    """Remove Iris' timestamped ``Properties.store`` output after the client exits.

    Iris rewrites ``shaderpacks/<pack>.zip.txt`` with Java ``Properties.store`` at
    runtime. Its first comment contains the wall-clock time, so otherwise identical
    render profiles end with different bytes. Parse and re-serialize Iris' observed
    mapping rather than replacing it with the requested mapping, so normalization
    cannot conceal runtime canonicalization, default omission, or value drift.
    """

    shaderpack = _validate_shaderpack_filename(shaderpack)
    if shaderpack is None:  # Kept explicit for type narrowing and defensive reuse.
        raise ValueError("Runtime Iris sidecar normalization requires one shader ZIP")
    sidecar = work_dir / "shaderpacks" / f"{shaderpack}.txt"
    try:
        runtime_bytes = sidecar.read_bytes()
    except OSError as exc:
        raise RuntimeError(
            f"Cannot read runtime Iris shader sidecar: {sidecar}"
        ) from exc

    observed = validate_shader_options(parse_java_properties(runtime_bytes))

    _atomic_write_bytes(
        sidecar,
        serialize_java_properties(observed, comment=_SHADER_OPTIONS_COMMENT),
    )
    return sidecar


def serialize_java_properties(
    properties: Mapping[str, str],
    *,
    comment: str | None = None,
) -> bytes:
    """Serialize Java properties with deterministic ordering and ASCII escaping."""

    if not isinstance(properties, Mapping):
        raise TypeError("Java properties must be a mapping")
    normalized: dict[str, str] = {}
    for key, value in properties.items():
        if not isinstance(key, str) or not isinstance(value, str):
            raise TypeError("Java property keys and values must be strings")
        normalized[key] = value

    lines = [] if comment is None else [f"# {comment}"]
    lines.extend(
        f"{_escape_java_property(key, escape_all_spaces=True)}="
        f"{_escape_java_property(value, escape_all_spaces=False)}"
        for key, value in sorted(normalized.items())
    )
    return ("\n".join(lines) + "\n").encode("ascii")


def parse_java_properties(data: bytes) -> dict[str, str]:
    """Parse the Java-properties subset emitted by Iris, including Java escapes."""

    try:
        text = data.decode("iso-8859-1")
    except UnicodeDecodeError as exc:  # pragma: no cover - latin-1 decodes every byte
        raise ValueError("Iris shader sidecar is not Java-properties data") from exc

    properties: dict[str, str] = {}
    for line in _logical_java_property_lines(text):
        stripped = line.lstrip(" \t\f")
        if not stripped or stripped.startswith(("#", "!")):
            continue
        key_raw, value_raw = _split_java_property(stripped)
        key = _unescape_java_property(key_raw)
        value = _unescape_java_property(value_raw)
        if key in properties:
            raise ValueError(f"Duplicate Java property key: {key!r}")
        properties[key] = value
    return properties


def _logical_java_property_lines(text: str) -> list[str]:
    logical: list[str] = []
    pending = ""
    continued = False
    for physical in text.splitlines():
        part = physical.lstrip(" \t\f") if continued else physical
        pending += part
        trailing_backslashes = len(pending) - len(pending.rstrip("\\"))
        if trailing_backslashes % 2 == 1:
            pending = pending[:-1]
            continued = True
            continue
        logical.append(pending)
        pending = ""
        continued = False
    if continued:
        logical.append(pending)
    return logical


def _split_java_property(line: str) -> tuple[str, str]:
    escaped = False
    key_end = len(line)
    separator_at: int | None = None
    for index, char in enumerate(line):
        if escaped:
            escaped = False
            continue
        if char == "\\":
            escaped = True
            continue
        if char in "=:":
            key_end = index
            separator_at = index
            break
        if char in " \t\f":
            key_end = index
            separator_at = index
            break

    value_start = key_end
    if separator_at is not None:
        value_start = separator_at
        while value_start < len(line) and line[value_start] in " \t\f":
            value_start += 1
        if value_start < len(line) and line[value_start] in "=:":
            value_start += 1
        while value_start < len(line) and line[value_start] in " \t\f":
            value_start += 1
    return line[:key_end], line[value_start:]


def _escape_java_property(value: str, *, escape_all_spaces: bool) -> str:
    escaped: list[str] = []
    for index, char in enumerate(value):
        replacements = {
            "\\": "\\\\",
            "\t": "\\t",
            "\n": "\\n",
            "\r": "\\r",
            "\f": "\\f",
        }
        if char in replacements:
            escaped.append(replacements[char])
        elif char == " " and (escape_all_spaces or index == 0):
            escaped.append("\\ ")
        elif char in "=:#!":
            escaped.append(f"\\{char}")
        elif ord(char) < 0x20 or ord(char) > 0x7E:
            encoded = char.encode("utf-16-be")
            escaped.extend(
                f"\\u{int.from_bytes(encoded[offset : offset + 2], 'big'):04X}"
                for offset in range(0, len(encoded), 2)
            )
        else:
            escaped.append(char)
    return "".join(escaped)


def _unescape_java_property(value: str) -> str:
    result: list[str] = []
    index = 0
    replacements = {"t": "\t", "n": "\n", "r": "\r", "f": "\f"}
    while index < len(value):
        char = value[index]
        if char != "\\":
            result.append(char)
            index += 1
            continue
        index += 1
        if index >= len(value):
            result.append("\\")
            break
        escaped = value[index]
        if escaped == "u":
            digits = value[index + 1 : index + 5]
            if len(digits) != 4 or not all(
                char in "0123456789abcdefABCDEF" for char in digits
            ):
                raise ValueError("Invalid Java property Unicode escape")
            result.append(chr(int(digits, 16)))
            index += 5
            continue
        result.append(replacements.get(escaped, escaped))
        index += 1
    decoded = "".join(result)
    # Java strings retain supplementary code points as UTF-16 surrogate pairs;
    # combine those pairs back into Python code points after processing \uXXXX.
    return decoded.encode("utf-16", errors="surrogatepass").decode("utf-16")


def _atomic_write_bytes(path: Path, payload: bytes) -> None:
    tmp = path.with_name(f".{path.name}.mcdata.tmp")
    try:
        tmp.write_bytes(payload)
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def _validate_shaderpack_filename(shaderpack: str | None) -> str | None:
    if shaderpack is None:
        return None
    if (
        not isinstance(shaderpack, str)
        or not shaderpack
        or Path(shaderpack).name != shaderpack
        or "/" in shaderpack
        or "\\" in shaderpack
        or "\n" in shaderpack
        or "\r" in shaderpack
        or not shaderpack.lower().endswith(".zip")
    ):
        raise ValueError(f"Iris shaderpack must be one safe ZIP filename: {shaderpack!r}")
    return shaderpack
