from __future__ import annotations

from pathlib import Path


QUALITY_OPTIONS: dict[str, dict[str, str]] = {
    "low": {
        "graphicsMode": "fast",
        "renderDistance": "2",
        "simulationDistance": "5",
        "entityDistanceScaling": "0.5",
        "ao": "false",
        "biomeBlendRadius": "0",
        "renderClouds": '"false"',
        "particles": "0",
        "maxFps": "120",
        "enableVsync": "false",
        "bobView": "false",
        "fov": "0.0",
    },
    "medium": {
        "graphicsMode": "fancy",
        "renderDistance": "8",
        "simulationDistance": "5",
        "entityDistanceScaling": "1.0",
        "ao": "true",
        "biomeBlendRadius": "1",
        "renderClouds": '"false"',
        "particles": "1",
        "maxFps": "120",
        "enableVsync": "false",
    },
    "high": {
        "graphicsMode": "fabulous",
        "renderDistance": "12",
        "simulationDistance": "6",
        "entityDistanceScaling": "1.0",
        "ao": "true",
        "biomeBlendRadius": "2",
        "renderClouds": '"true"',
        "particles": "2",
        "maxFps": "120",
        "enableVsync": "false",
    },
}


QUIET_CAPTURE_OPTIONS: dict[str, str] = {
    "advancedItemTooltips": "false",
    "chatVisibility": "2",
    "joinedFirstServer": "true",
    "notificationDisplayTime": "1.0",
    "pauseOnLostFocus": "false",
    "showAutosaveIndicator": "false",
    "showSubtitles": "false",
    "skipMultiplayerWarning": "true",
    "tutorialStep": "none",
}


def write_options(
    work_dir: Path,
    *,
    quality: str,
    resourcepacks: list[str],
    overrides: dict[str, str] | None = None,
    quiet_capture: bool = True,
) -> None:
    options = dict(QUALITY_OPTIONS.get(quality, QUALITY_OPTIONS["low"]))
    if quiet_capture:
        options.update(QUIET_CAPTURE_OPTIONS)
    if overrides:
        options.update({str(key): str(value) for key, value in overrides.items()})
    if resourcepacks:
        options["resourcePacks"] = "[" + ",".join(f'"file/{name}"' for name in resourcepacks) + "]"
        options["incompatibleResourcePacks"] = "[]"

    lines = [f"{key}:{value}" for key, value in sorted(options.items())]
    (work_dir / "options.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_iris_config(work_dir: Path, *, shaderpack: str | None, enabled: bool) -> None:
    config_dir = work_dir / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "iris.properties").write_text(
        "\n".join(
            [
                "# Generated by mcdata.",
                f"enableShaders={'true' if enabled and shaderpack else 'false'}",
                f"shaderPack={shaderpack or ''}",
                "",
            ]
        ),
        encoding="utf-8",
    )
