from __future__ import annotations

import re
from collections.abc import Mapping
from pathlib import Path


QUALITY_OPTIONS: dict[str, dict[str, str]] = {
    "low": {
        "graphicsMode": "fast",
        "renderDistance": "2",
        "simulationDistance": "5",
        "entityDistanceScaling": "0.5",
        "ao": "false",
        "biomeBlendRadius": "0",
        "renderClouds": '"false"',
        "particles": "0",
        "maxFps": "120",
        "enableVsync": "false",
        "bobView": "false",
        "fov": "0.0",
    },
    "medium": {
        "graphicsMode": "fancy",
        "renderDistance": "8",
        "simulationDistance": "5",
        "entityDistanceScaling": "1.0",
        "ao": "true",
        "biomeBlendRadius": "1",
        "renderClouds": '"false"',
        "particles": "1",
        "maxFps": "120",
        "enableVsync": "false",
    },
    "high": {
        "graphicsMode": "fabulous",
        "renderDistance": "12",
        "simulationDistance": "6",
        "entityDistanceScaling": "1.0",
        "ao": "true",
        "biomeBlendRadius": "2",
        "renderClouds": '"true"',
        "particles": "2",
        "maxFps": "120",
        "enableVsync": "false",
    },
}


QUIET_CAPTURE_OPTIONS: dict[str, str] = {
    "advancedItemTooltips": "false",
    "chatVisibility": "2",
    "inGameNotification": "false",
    "joinedFirstServer": "true",
    "mouseSensitivity": "0.5",
    "musicToast": '"never"',
    "notificationDisplayTime": "0.5",
    "pauseOnLostFocus": "false",
    "rawMouseInput": "true",
    "realmsNotifications": "false",
    "showAutosaveIndicator": "false",
    "showSubtitles": "false",
    "skipMultiplayerWarning": "true",
    "tutorialStep": "none",
}

_SHADER_OPTION_KEY_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
_SHADER_OPTION_VALUE_RE = re.compile(r"[A-Za-z0-9_.+\-]+\Z")


def write_options(
    work_dir: Path,
    *,
    quality: str,
    resourcepacks: list[str],
    overrides: dict[str, str] | None = None,
    quiet_capture: bool = True,
) -> None:
    options = dict(QUALITY_OPTIONS.get(quality, QUALITY_OPTIONS["low"]))
    if quiet_capture:
        options.update(QUIET_CAPTURE_OPTIONS)
    if overrides:
        options.update({str(key): str(value) for key, value in overrides.items()})
    if resourcepacks:
        options["resourcePacks"] = "[" + ",".join(f'"file/{name}"' for name in resourcepacks) + "]"
        options["incompatibleResourcePacks"] = "[]"

    lines = [f"{key}:{value}" for key, value in sorted(options.items())]
    (work_dir / "options.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


def validate_shader_options(options: Mapping[str, str] | None) -> dict[str, str]:
    if options is None:
        return {}
    if not isinstance(options, Mapping):
        raise ValueError("Iris shader_options must be a mapping of string keys to string values")

    normalized: dict[str, str] = {}
    for key, value in options.items():
        if not isinstance(key, str) or not _SHADER_OPTION_KEY_RE.fullmatch(key):
            raise ValueError(
                "Iris shader option keys must be GLSL-style identifiers "
                f"(invalid key: {key!r})"
            )
        if not isinstance(value, str) or not _SHADER_OPTION_VALUE_RE.fullmatch(value):
            raise ValueError(
                "Iris shader option values must be non-empty, single-token strings "
                f"(invalid value for {key!r}: {value!r})"
            )
        normalized[key] = value
    return dict(sorted(normalized.items()))


def write_iris_config(
    work_dir: Path,
    *,
    shaderpack: str | None,
    enabled: bool,
    shader_options: Mapping[str, str] | None = None,
) -> None:
    options = validate_shader_options(shader_options)
    shaderpack = _validate_shaderpack_filename(shaderpack)
    if options and shaderpack is None:
        raise ValueError("Iris shader_options require exactly one selected shader ZIP")

    config_dir = work_dir / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "iris.properties").write_text(
        "\n".join(
            [
                "# Generated by mcdata.",
                f"enableShaders={'true' if enabled and shaderpack else 'false'}",
                f"shaderPack={shaderpack or ''}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    if shaderpack is None:
        return
    sidecar = work_dir / "shaderpacks" / f"{shaderpack}.txt"
    sidecar.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by mcdata.", *(f"{key}={value}" for key, value in options.items())]
    sidecar.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _validate_shaderpack_filename(shaderpack: str | None) -> str | None:
    if shaderpack is None:
        return None
    if (
        not isinstance(shaderpack, str)
        or not shaderpack
        or Path(shaderpack).name != shaderpack
        or "/" in shaderpack
        or "\\" in shaderpack
        or "\n" in shaderpack
        or "\r" in shaderpack
        or not shaderpack.lower().endswith(".zip")
    ):
        raise ValueError(f"Iris shaderpack must be one safe ZIP filename: {shaderpack!r}")
    return shaderpack
