from pathlib import Path

import pytest

from mcdata.render.options import (
    QUIET_CAPTURE_OPTIONS,
    canonicalize_iris_shader_options_sidecar,
    parse_java_properties,
    serialize_java_properties,
    write_iris_config,
    write_options,
)

ROOT = Path(__file__).resolve().parents[1]


def _read_options(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        key, value = line.split(":", 1)
        values[key] = value
    return values


def test_write_options_includes_quiet_capture_keys(tmp_path: Path) -> None:
    write_options(tmp_path, quality="low", resourcepacks=[])
    options = _read_options(tmp_path / "options.txt")

    for key, value in QUIET_CAPTURE_OPTIONS.items():
        assert options[key] == value
    assert options["rawMouseInput"] == "true"
    assert options["mouseSensitivity"] == "0.5"
    assert options["notificationDisplayTime"] == "0.5"
    assert options["inGameNotification"] == "false"
    assert options["musicToast"] == '"never"'
    assert options["realmsNotifications"] == "false"


def test_write_options_resourcepack_format(tmp_path: Path) -> None:
    write_options(tmp_path, quality="low", resourcepacks=["a.zip", "b.zip"])
    options = _read_options(tmp_path / "options.txt")

    assert options["resourcePacks"] == '["file/a.zip","file/b.zip"]'
    assert options["incompatibleResourcePacks"] == "[]"


def test_write_iris_config_with_shaderpack(tmp_path: Path) -> None:
    write_iris_config(tmp_path, shaderpack="example.zip", enabled=True)

    text = (tmp_path / "config" / "iris.properties").read_text(encoding="utf-8")
    assert "enableShaders=true" in text
    assert "shaderPack=example.zip" in text
    assert (tmp_path / "shaderpacks" / "example.zip.txt").read_text(
        encoding="utf-8"
    ) == "# Generated by mcdata.\n"


def test_write_iris_config_writes_deterministic_shader_sidecar(tmp_path: Path) -> None:
    write_iris_config(
        tmp_path,
        shaderpack="Solas Shader V3.7.zip",
        enabled=True,
        shader_options={"WATER_REFLECTIONS": "true", "MATERIAL_FORMAT": "1"},
    )

    actual = (tmp_path / "shaderpacks" / "Solas Shader V3.7.zip.txt").read_bytes()
    expected = (ROOT / "tests" / "golden" / "iris_shader_options.txt").read_bytes()
    assert actual == expected


def test_java_properties_serializer_has_stable_java_escapes_and_byte_golden() -> None:
    properties = {
        "z key": " leading value",
        "punct:=#!": "line1\nline2\t\\end",
        "emoji": "雪🌙",
    }

    actual = serialize_java_properties(properties, comment="Generated by mcdata.")
    expected = (ROOT / "tests" / "golden" / "java_properties_escaped.txt").read_bytes()

    assert actual == expected
    assert parse_java_properties(actual) == properties


def test_runtime_iris_sidecar_timestamp_is_canonicalized_idempotently(
    tmp_path: Path,
) -> None:
    sidecar = tmp_path / "shaderpacks" / "Solas Shader V3.7.zip.txt"
    sidecar.parent.mkdir(parents=True)
    sidecar.write_bytes(
        b"#Fri Jul 10 16:01:56 UTC 2026\r\nWATER_REFLECTIONS=true\r\nMATERIAL_FORMAT=1\r\n"
    )
    expected = (ROOT / "tests" / "golden" / "iris_shader_options.txt").read_bytes()

    canonicalize_iris_shader_options_sidecar(
        tmp_path,
        shaderpack="Solas Shader V3.7.zip",
    )
    first = sidecar.read_bytes()
    canonicalize_iris_shader_options_sidecar(
        tmp_path,
        shaderpack="Solas Shader V3.7.zip",
    )

    assert first == expected
    assert sidecar.read_bytes() == first
    assert b"Jul 10" not in first


def test_runtime_iris_sidecar_observed_values_are_preserved(tmp_path: Path) -> None:
    sidecar = tmp_path / "shaderpacks" / "example.zip.txt"
    sidecar.parent.mkdir(parents=True)
    runtime = b"#Fri Jul 10 16:01:56 UTC 2026\nMATERIAL_FORMAT=0\n"
    sidecar.write_bytes(runtime)

    canonicalize_iris_shader_options_sidecar(
        tmp_path,
        shaderpack="example.zip",
    )

    assert sidecar.read_bytes() == b"# Generated by mcdata.\nMATERIAL_FORMAT=0\n"


def test_runtime_iris_sidecar_duplicate_key_is_rejected_without_rewriting(
    tmp_path: Path,
) -> None:
    sidecar = tmp_path / "shaderpacks" / "example.zip.txt"
    sidecar.parent.mkdir(parents=True)
    runtime = b"# timestamp\nMATERIAL_FORMAT=0\nMATERIAL_FORMAT=1\n"
    sidecar.write_bytes(runtime)

    with pytest.raises(ValueError, match="Duplicate Java property key"):
        canonicalize_iris_shader_options_sidecar(
            tmp_path,
            shaderpack="example.zip",
        )

    assert sidecar.read_bytes() == runtime


def test_write_iris_config_clears_stale_selected_sidecar_when_options_are_empty(
    tmp_path: Path,
) -> None:
    sidecar = tmp_path / "shaderpacks" / "example.zip.txt"
    sidecar.parent.mkdir(parents=True)
    sidecar.write_text("STALE=true\n", encoding="utf-8")

    write_iris_config(tmp_path, shaderpack="example.zip", enabled=True, shader_options={})

    assert sidecar.read_text(encoding="utf-8") == "# Generated by mcdata.\n"


def test_write_iris_config_without_shaderpack(tmp_path: Path) -> None:
    write_iris_config(tmp_path, shaderpack=None, enabled=True)

    text = (tmp_path / "config" / "iris.properties").read_text(encoding="utf-8")
    assert "enableShaders=false" in text
    assert "shaderPack=" in text


def test_write_iris_config_rejects_options_without_shader_before_writing(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="exactly one selected shader ZIP"):
        write_iris_config(
            tmp_path,
            shaderpack=None,
            enabled=False,
            shader_options={"MATERIAL_FORMAT": "1"},
        )

    assert not (tmp_path / "config").exists()
    assert not (tmp_path / "shaderpacks").exists()


@pytest.mark.parametrize(
    ("options", "error"),
    [
        ({"BAD\nKEY": "true"}, "keys must be GLSL-style identifiers"),
        ({"GOOD_KEY": "two tokens"}, "values must be non-empty, single-token strings"),
        ({"GOOD_KEY": True}, "values must be non-empty, single-token strings"),
    ],
)
def test_write_iris_config_rejects_unsafe_shader_options(
    tmp_path: Path,
    options: dict[object, object],
    error: str,
) -> None:
    with pytest.raises(ValueError, match=error):
        write_iris_config(
            tmp_path,
            shaderpack="example.zip",
            enabled=True,
            shader_options=options,  # type: ignore[arg-type]
        )

    assert not (tmp_path / "config").exists()


@pytest.mark.parametrize("shaderpack", ["../escape.zip", "nested/escape.zip", "not-a-zip"])
def test_write_iris_config_rejects_unsafe_shaderpack_filename(
    tmp_path: Path,
    shaderpack: str,
) -> None:
    with pytest.raises(ValueError, match="one safe ZIP filename"):
        write_iris_config(
            tmp_path,
            shaderpack=shaderpack,
            enabled=True,
            shader_options={"MATERIAL_FORMAT": "1"},
        )

    assert not (tmp_path / "config").exists()
